"""Human approval contracts, rules, and policy helpers."""

from app.approvals.events import (
    APPROVAL_APPROVED_EVENT,
    APPROVAL_CHANGES_REQUESTED_EVENT,
    APPROVAL_EVENT_NAMES,
    APPROVAL_REJECTED_EVENT,
    APPROVAL_REQUESTED_EVENT,
    WORKFLOW_RESUME_FAILED_EVENT,
    WORKFLOW_RESUME_REQUESTED_EVENT,
    WORKFLOW_RESUMED_EVENT,
)
from app.approvals.exceptions import (
    ApprovalInvalidStateError,
    ApprovalLifecycleError,
    ApprovalTerminalStateError,
    DuplicateFinalApprovalDecisionError,
    ResumeNotAllowedError,
)
from app.approvals.lifecycle import (
    FINAL_APPROVAL_DECISIONS,
    NON_FINAL_APPROVAL_DECISIONS,
    get_allowed_approval_decisions,
    get_next_status_for_decision,
    get_resume_allowed_after_decision,
    has_final_approval_decision,
    is_final_approval_decision,
    validate_approval_decision_allowed,
    validate_resume_allowed,
)
from app.approvals.policies import (
    APPROVAL_FINAL_DECISION_ROLES,
    APPROVAL_READ_ROLES,
    APPROVAL_REQUEST_CHANGES_ROLES,
    APPROVAL_RESUME_ROLES,
    can_read_approval_history,
    can_resume_workflow,
    can_submit_approval_decision,
)
from app.approvals.schemas import (
    ApprovalDecisionRequest,
    ApprovalDecisionResponse,
    ApprovalDecisionType,
    ApprovalHistoryResponse,
    ApprovalRecord,
    WorkflowResumeRequest,
    WorkflowResumeResponse,
)

__all__ = [
    "APPROVAL_APPROVED_EVENT",
    "APPROVAL_CHANGES_REQUESTED_EVENT",
    "APPROVAL_EVENT_NAMES",
    "APPROVAL_FINAL_DECISION_ROLES",
    "APPROVAL_READ_ROLES",
    "APPROVAL_REJECTED_EVENT",
    "APPROVAL_REQUESTED_EVENT",
    "APPROVAL_REQUEST_CHANGES_ROLES",
    "APPROVAL_RESUME_ROLES",
    "FINAL_APPROVAL_DECISIONS",
    "NON_FINAL_APPROVAL_DECISIONS",
    "WORKFLOW_RESUMED_EVENT",
    "WORKFLOW_RESUME_FAILED_EVENT",
    "WORKFLOW_RESUME_REQUESTED_EVENT",
    "ApprovalDecisionRequest",
    "ApprovalDecisionResponse",
    "ApprovalDecisionType",
    "ApprovalHistoryResponse",
    "ApprovalInvalidStateError",
    "ApprovalLifecycleError",
    "ApprovalRecord",
    "ApprovalTerminalStateError",
    "DuplicateFinalApprovalDecisionError",
    "ResumeNotAllowedError",
    "WorkflowResumeRequest",
    "WorkflowResumeResponse",
    "can_read_approval_history",
    "can_resume_workflow",
    "can_submit_approval_decision",
    "get_allowed_approval_decisions",
    "get_next_status_for_decision",
    "get_resume_allowed_after_decision",
    "has_final_approval_decision",
    "is_final_approval_decision",
    "validate_approval_decision_allowed",
    "validate_resume_allowed",
]
