"""Provider-independent knowledge base contracts and chunking helpers."""

from app.knowledge.chunking import (
    build_chunk_id,
    chunk_document,
    normalize_knowledge_text,
    sha256_normalized_text,
)
from app.knowledge.embeddings import (
    EmbeddingBatchResult,
    EmbeddingClient,
    EmbeddingErrorCategory,
    EmbeddingInput,
    EmbeddingModelCapabilities,
    EmbeddingProviderName,
    EmbeddingRequest,
    EmbeddingResult,
    EmbeddingService,
    EmbeddingSettings,
    EmbeddingVectorMetadata,
    FakeEmbeddingClient,
    create_embedding_client,
    create_embedding_service,
)
from app.knowledge.schemas import (
    ChunkingConfig,
    ChunkingResult,
    KnowledgeChunk,
    KnowledgeChunkMetadata,
    KnowledgeCitation,
    KnowledgeDocument,
    KnowledgeDocumentMetadata,
    KnowledgeDocumentSourceType,
    KnowledgeRetrievalResult,
    KnowledgeSearchRequest,
    KnowledgeSearchResponse,
)

__all__ = [
    "ChunkingConfig",
    "ChunkingResult",
    "EmbeddingBatchResult",
    "EmbeddingClient",
    "EmbeddingErrorCategory",
    "EmbeddingInput",
    "EmbeddingModelCapabilities",
    "EmbeddingProviderName",
    "EmbeddingRequest",
    "EmbeddingResult",
    "EmbeddingService",
    "EmbeddingSettings",
    "EmbeddingVectorMetadata",
    "FakeEmbeddingClient",
    "KnowledgeChunk",
    "KnowledgeChunkMetadata",
    "KnowledgeCitation",
    "KnowledgeDocument",
    "KnowledgeDocumentMetadata",
    "KnowledgeDocumentSourceType",
    "KnowledgeRetrievalResult",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "build_chunk_id",
    "chunk_document",
    "create_embedding_client",
    "create_embedding_service",
    "normalize_knowledge_text",
    "sha256_normalized_text",
]
