"""Runtime state contracts and adapter helpers."""

from app.runtime.graph import (
    CompiledWorkflowGraph,
    RuntimeGraphEdge,
    RuntimeNodeHandler,
    RuntimeNodeHandlers,
    RuntimeStatePayload,
    build_workflow_graph,
    runtime_graph_topology,
    runtime_stage_sequence,
    validate_runtime_node_handlers,
)
from app.runtime.llm_adapter import LLMCompletionService, LLMRuntimeAdapter
from app.runtime.nodes import (
    create_deterministic_node_handlers,
    run_approval_node,
    run_compliance_node,
    run_email_preparation_node,
    run_planner_node,
    run_quotation_node,
    run_retrieval_node,
    run_validation_node,
)
from app.runtime.rag_adapter import (
    KNOWLEDGE_GROUNDING_COMPLETED_EVENT,
    KNOWLEDGE_GROUNDING_FAILED_EVENT,
    KNOWLEDGE_GROUNDING_STARTED_EVENT,
    RAG_SUPPORTED_STAGES,
    KnowledgeRetrievalServiceProtocol,
    RuntimeRAGGroundingAdapter,
)
from app.runtime.schemas import (
    RUNTIME_STAGES,
    RuntimeStage,
    RuntimeWorkflowResult,
    RuntimeWorkflowState,
    runtime_stage_values,
)
from app.runtime.service import (
    POST_APPROVAL_RUNTIME_STAGES,
    PRE_APPROVAL_RUNTIME_STAGES,
    RUNTIME_STAGE_STATUSES,
    RuntimeService,
    WorkflowRuntimeError,
    WorkflowRuntimeNodeError,
    WorkflowRuntimePreconditionError,
)
from app.runtime.state_adapter import (
    RuntimeStateAdapterError,
    runtime_state_to_workflow_state,
    workflow_state_to_runtime_state,
)

__all__ = [
    "POST_APPROVAL_RUNTIME_STAGES",
    "PRE_APPROVAL_RUNTIME_STAGES",
    "RUNTIME_STAGES",
    "RUNTIME_STAGE_STATUSES",
    "CompiledWorkflowGraph",
    "LLMCompletionService",
    "LLMRuntimeAdapter",
    "KNOWLEDGE_GROUNDING_COMPLETED_EVENT",
    "KNOWLEDGE_GROUNDING_FAILED_EVENT",
    "KNOWLEDGE_GROUNDING_STARTED_EVENT",
    "KnowledgeRetrievalServiceProtocol",
    "RAG_SUPPORTED_STAGES",
    "RuntimeGraphEdge",
    "RuntimeNodeHandler",
    "RuntimeNodeHandlers",
    "RuntimeRAGGroundingAdapter",
    "RuntimeService",
    "RuntimeStage",
    "RuntimeStatePayload",
    "RuntimeStateAdapterError",
    "RuntimeWorkflowResult",
    "RuntimeWorkflowState",
    "WorkflowRuntimeError",
    "WorkflowRuntimeNodeError",
    "WorkflowRuntimePreconditionError",
    "build_workflow_graph",
    "create_deterministic_node_handlers",
    "runtime_graph_topology",
    "runtime_stage_sequence",
    "runtime_stage_values",
    "runtime_state_to_workflow_state",
    "run_approval_node",
    "run_compliance_node",
    "run_email_preparation_node",
    "run_planner_node",
    "run_quotation_node",
    "run_retrieval_node",
    "run_validation_node",
    "validate_runtime_node_handlers",
    "workflow_state_to_runtime_state",
]
